spring.application.name=bytezone

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?
spring.datasource.username=postgres.meoafrjeldzhxjbhidjo
spring.datasource.password=Lichael123456!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

jwt.secret=yourSuperSecretKeyForByteZoneJwt123456
jwt.expiration=86400000

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.transaction=TRACE
logging.level.org.springframework.orm.jpa=DEBUG